var searchData=
[
  ['emitsignal_0',['emitSignal',['../classqt__signals_1_1QtSignalsExample.html#ade4211730232a696cbaa6829cbc86dcb',1,'qt_signals::QtSignalsExample']]],
  ['emitter_1',['Example: Node.js Event Emitter',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md58',1,'']]],
  ['error_2',['error',['../namespacecommon.html#aa3dd8c5983888f4c0199cf0bb2a73b2aa902b0d55fddef6f8d651fe1035b7d4bd',1,'common::Error'],['../classcommon_1_1Logger.html#aec9c7a7111c70e5f9b4e13aa71cc805f',1,'common::Logger::error()']]],
  ['error_20handling_20and_20debugging_3',['Error Handling and Debugging',['../md_build_2md__files_2docs_2design.html#autotoc_md35',1,'']]],
  ['event_4',['event',['../classevent__queue_1_1EventQueue.html#ab89b2fd741da44f28c564c0109f0746d',1,'event_queue::EventQueue::Event'],['../classcallbacks_1_1Event.html',1,'callbacks::Event']]],
  ['event_20driven_20programming_5',['Benefits of Event-Driven Programming',['../md_build_2md__files_2docs_2what__is__event__driven__programming.html#autotoc_md140',1,'']]],
  ['event_20driven_20programming_20across_20languages_6',['Comparing Event-Driven Programming Across Languages',['../md_build_2md__files_2docs_2event__driven__comparison.html',1,'']]],
  ['event_20driven_20programming_20in_20c_7',['event driven programming in c',['../md_build_2md__files_2docs_2design.html',1,'Design Considerations for Event-Driven Programming in C++'],['../index.html',1,'Event-Driven Programming in C++'],['../md_build_2md__files_2docs_2what__is__event__driven__programming.html',1,'Event-Driven Programming in C++'],['../md_build_2md__files_2docs_2setup.html',1,'Setup Guide for Event-Driven Programming in C++']]],
  ['event_20driven_20programming_20vs_20event_20driven_20architecture_8',['Event-Driven Programming vs. Event-Driven Architecture',['../md_build_2md__files_2docs_2what__is__event__driven__programming.html#autotoc_md139',1,'']]],
  ['event_20driven_20programming_20works_9',['How Event-Driven Programming Works',['../md_build_2md__files_2docs_2what__is__event__driven__programming.html#autotoc_md136',1,'']]],
  ['event_20emitter_10',['Example: Node.js Event Emitter',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md58',1,'']]],
  ['event_20handling_11',['Example: Swing Event Handling',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md47',1,'']]],
  ['event_20handling_20with_20tt_20select_20tt_20tt_20poll_20tt_12',['4. I/O Event Handling with &lt;tt&gt;select()&lt;/tt&gt;/&lt;tt&gt;poll()&lt;/tt&gt;',['../md_build_2md__files_2docs_2design.html#autotoc_md30',1,'']]],
  ['event_20in_20the_20browser_13',['Example: DOM Event in the Browser',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md57',1,'']]],
  ['event_20queue_20example_14',['Event Queue Example',['../md_src_2event__queue_2README.html',1,'']]],
  ['event_20queue_20in_20c_15',['Event Queue in C++',['../md_build_2md__files_2docs_2event__queue.html',1,'']]],
  ['event_20queues_16',['5. Message/Event Queues',['../md_build_2md__files_2docs_2design.html#autotoc_md31',1,'']]],
  ['event_5fdriven_5fcomparison_2emd_17',['event_driven_comparison.md',['../event__driven__comparison_8md.html',1,'']]],
  ['event_5fqueue_18',['event_queue',['../namespaceevent__queue.html',1,'']]],
  ['event_5fqueue_2ecpp_19',['event_queue.cpp',['../event__queue_8cpp.html',1,'']]],
  ['event_5fqueue_2ehpp_20',['event_queue.hpp',['../event__queue_8hpp.html',1,'']]],
  ['event_5fqueue_2emd_21',['event_queue.md',['../event__queue_8md.html',1,'']]],
  ['event_5fqueue_5ftest_2ecpp_22',['event_queue_test.cpp',['../event__queue__test_8cpp.html',1,'']]],
  ['eventqueue_23',['EventQueue',['../classevent__queue_1_1EventQueue.html',1,'event_queue']]],
  ['events_5f_24',['events_',['../classevent__queue_1_1EventQueue.html#a6a55ae6457ab9f980ce2e39b16aa14a2',1,'event_queue::EventQueue']]],
  ['example_25',['example',['../md_build_2md__files_2docs_2event__queue.html#autotoc_md67',1,'A Simple C++ Example'],['../md_src_2event__queue_2README.html#autotoc_md157',1,'Building the Example'],['../md_src_2callbacks_2README.html#autotoc_md145',1,'Building the Example'],['../md_src_2observer_2README.html#autotoc_md178',1,'Building the Example'],['../md_src_2qt__signals_2README.html#autotoc_md184',1,'Building the Example'],['../md_src_2callbacks_2README.html',1,'Callbacks Example'],['../md_src_2event__queue_2README.html',1,'Event Queue Example'],['../md_src_2observer_2README.html',1,'Observer Pattern Example'],['../md_src_2qt__signals_2README.html#autotoc_md188',1,'Overview of the Example'],['../md_src_2qt__signals_2README.html',1,'Qt Signals &amp; Slots Example'],['../md_src_2qt__signals_2README.html#autotoc_md187',1,'Running the Example'],['../md_src_2observer_2README.html#autotoc_md179',1,'Running the Example'],['../md_src_2event__queue_2README.html#autotoc_md160',1,'Running the Example'],['../md_src_2callbacks_2README.html#autotoc_md146',1,'Running the Example'],['../index.html#autotoc_md7',1,'Test Mode for I/O and Sockets Example']]],
  ['example_20code_26',['Example Code',['../md_build_2md__files_2docs_2event__queue.html#autotoc_md68',1,'']]],
  ['example_20implementation_27',['Example Implementation',['../md_build_2md__files_2docs_2observer.html#autotoc_md92',1,'']]],
  ['example_3a_20a_20simple_20signal_20slot_20implementation_28',['Example: A Simple Signal-Slot Implementation',['../md_build_2md__files_2docs_2qt__signals.html#autotoc_md112',1,'']]],
  ['example_3a_20asyncio_29',['Example: Asyncio',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md52',1,'']]],
  ['example_3a_20dom_20event_20in_20the_20browser_30',['Example: DOM Event in the Browser',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md57',1,'']]],
  ['example_3a_20gui_20application_31',['Example: GUI Application',['../md_build_2md__files_2docs_2what__is__event__driven__programming.html#autotoc_md137',1,'']]],
  ['example_3a_20network_20server_32',['Example: Network Server',['../md_build_2md__files_2docs_2what__is__event__driven__programming.html#autotoc_md138',1,'']]],
  ['example_3a_20node_20js_20event_20emitter_33',['Example: Node.js Event Emitter',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md58',1,'']]],
  ['example_3a_20observer_20pattern_34',['Example: Observer Pattern',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md42',1,'']]],
  ['example_3a_20swing_20event_20handling_35',['Example: Swing Event Handling',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md47',1,'']]],
  ['examples_36',['Running the Examples',['../index.html#autotoc_md5',1,'']]],
  ['explanation_37',['explanation',['../md_build_2md__files_2docs_2qt__signals.html#autotoc_md116',1,'Explanation'],['../md_build_2md__files_2docs_2event__queue.html#autotoc_md69',1,'Explanation']]]
];
