var searchData=
[
  ['a_20comparison_0',['Observer Pattern vs. Callbacks: A Comparison',['../md_build_2md__files_2docs_2observer__vs__callbacks.html',1,'']]],
  ['a_20qt_20project_1',['Setting Up a Qt Project',['../md_build_2md__files_2docs_2qt__signals.html#autotoc_md111',1,'']]],
  ['a_20simple_20c_20example_2',['A Simple C++ Example',['../md_build_2md__files_2docs_2event__queue.html#autotoc_md67',1,'']]],
  ['a_20simple_20signal_20slot_20implementation_3',['Example: A Simple Signal-Slot Implementation',['../md_build_2md__files_2docs_2qt__signals.html#autotoc_md112',1,'']]],
  ['across_20languages_4',['Comparing Event-Driven Programming Across Languages',['../md_build_2md__files_2docs_2event__driven__comparison.html',1,'']]],
  ['additional_20information_5',['Additional Information',['../md_src_2io__and__sockets_2README.html#autotoc_md175',1,'']]],
  ['additional_20notes_6',['Additional Notes',['../index.html#autotoc_md8',1,'']]],
  ['additional_20resources_7',['additional resources',['../md_src_2qt__signals_2README.html#autotoc_md189',1,'Additional Resources'],['../md_build_2md__files_2docs_2io__and__sockets.html#autotoc_md85',1,'Additional Resources'],['../md_build_2md__files_2docs_2README.html#autotoc_md14',1,'Additional Resources']]],
  ['addobserver_8',['addObserver',['../classobserver_1_1Subject.html#a544ee43d21c9347650505338df5f5753',1,'observer::Subject']]],
  ['advanced_20considerations_9',['Advanced Considerations',['../md_build_2md__files_2docs_2event__queue.html#autotoc_md70',1,'']]],
  ['and_20concepts_10',['Key Design Patterns and Concepts',['../md_build_2md__files_2docs_2design.html#autotoc_md26',1,'']]],
  ['and_20cons_11',['and cons',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md59',1,'Pros and Cons'],['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md43',1,'Pros and Cons'],['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md48',1,'Pros and Cons'],['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md53',1,'Pros and Cons']]],
  ['and_20debugging_12',['Error Handling and Debugging',['../md_build_2md__files_2docs_2design.html#autotoc_md35',1,'']]],
  ['and_20function_20pointers_13',['2. Callbacks and Function Pointers',['../md_build_2md__files_2docs_2design.html#autotoc_md28',1,'']]],
  ['and_20modularity_14',['Decoupling and Modularity',['../md_build_2md__files_2docs_2design.html#autotoc_md33',1,'']]],
  ['and_20responsiveness_15',['Concurrency and Responsiveness',['../md_build_2md__files_2docs_2design.html#autotoc_md34',1,'']]],
  ['and_20run_16',['How to Build and Run',['../md_build_2md__files_2docs_2io__and__sockets.html#autotoc_md80',1,'']]],
  ['and_20slots_17',['What Are Signals and Slots?',['../md_build_2md__files_2docs_2qt__signals.html#autotoc_md109',1,'']]],
  ['and_20sockets_20demonstration_18',['and sockets demonstration',['../md_src_2io__and__sockets_2README.html',1,'I/O and Sockets Demonstration'],['../md_build_2md__files_2docs_2io__and__sockets.html',1,'I/O and Sockets Demonstration']]],
  ['and_20sockets_20example_19',['Test Mode for I/O and Sockets Example',['../index.html#autotoc_md7',1,'']]],
  ['and_20vcinstalldir_20',['Note on Qt6_DIR and VCINSTALLDIR',['../md_build_2md__files_2docs_2setup.html#autotoc_md129',1,'']]],
  ['application_21',['application',['../md_build_2md__files_2docs_2what__is__event__driven__programming.html#autotoc_md137',1,'Example: GUI Application'],['../md_build_2md__files_2docs_2setup.html#autotoc_md131',1,'Running the Application']]],
  ['approaches_20to_20implementing_20callbacks_22',['Approaches to Implementing Callbacks',['../md_build_2md__files_2docs_2callbacks.html#autotoc_md17',1,'']]],
  ['architectural_20considerations_23',['Architectural Considerations',['../md_build_2md__files_2docs_2design.html#autotoc_md32',1,'']]],
  ['architecture_24',['Event-Driven Programming vs. Event-Driven Architecture',['../md_build_2md__files_2docs_2what__is__event__driven__programming.html#autotoc_md139',1,'']]],
  ['are_20callbacks_25',['What Are Callbacks?',['../md_build_2md__files_2docs_2callbacks.html#autotoc_md16',1,'']]],
  ['are_20signals_20and_20slots_26',['What Are Signals and Slots?',['../md_build_2md__files_2docs_2qt__signals.html#autotoc_md109',1,'']]],
  ['asyncio_27',['Example: Asyncio',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md52',1,'']]],
  ['automatic_20deployment_20on_20windows_28',['Automatic Deployment on Windows',['../md_build_2md__files_2docs_2setup.html#autotoc_md128',1,'']]]
];
