var searchData=
[
  ['c_0',['c',['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md40',1,'C++'],['../md_build_2md__files_2docs_2callbacks.html',1,'Callbacks in C++'],['../md_build_2md__files_2docs_2design.html',1,'Design Considerations for Event-Driven Programming in C++'],['../md_build_2md__files_2docs_2event__queue.html',1,'Event Queue in C++'],['../index.html',1,'Event-Driven Programming in C++'],['../md_build_2md__files_2docs_2what__is__event__driven__programming.html',1,'Event-Driven Programming in C++'],['../md_build_2md__files_2docs_2observer.html',1,'Observer Pattern in C++'],['../md_build_2md__files_2docs_2qt__signals.html',1,'Qt Signals &amp; Slots in C++'],['../md_build_2md__files_2docs_2setup.html',1,'Setup Guide for Event-Driven Programming in C++']]],
  ['c_20example_1',['A Simple C++ Example',['../md_build_2md__files_2docs_2event__queue.html#autotoc_md67',1,'']]],
  ['callback_2',['Callback',['../classcallbacks_1_1Event.html#ac5e390cce170616d162e0fe187ece788',1,'callbacks::Event']]],
  ['callback_5f_3',['callback_',['../classcallbacks_1_1Event.html#ac7e13b7eb097069cdd3b5f1efdc221b3',1,'callbacks::Event']]],
  ['callbacks_4',['callbacks',['../md_build_2md__files_2docs_2callbacks.html#autotoc_md17',1,'Approaches to Implementing Callbacks'],['../md_build_2md__files_2docs_2callbacks.html#autotoc_md21',1,'Benefits of Using Callbacks'],['../namespacecallbacks.html',1,'callbacks'],['../md_build_2md__files_2docs_2observer__vs__callbacks.html#autotoc_md101',1,'Callbacks'],['../md_build_2md__files_2docs_2callbacks.html#autotoc_md16',1,'What Are Callbacks?'],['../md_build_2md__files_2docs_2callbacks.html#autotoc_md22',1,'When to Use Callbacks']]],
  ['callbacks_20and_20function_20pointers_5',['2. Callbacks and Function Pointers',['../md_build_2md__files_2docs_2design.html#autotoc_md28',1,'']]],
  ['callbacks_20example_6',['Callbacks Example',['../md_src_2callbacks_2README.html',1,'']]],
  ['callbacks_20in_20c_7',['Callbacks in C++',['../md_build_2md__files_2docs_2callbacks.html',1,'']]],
  ['callbacks_2ecpp_8',['callbacks.cpp',['../callbacks_8cpp.html',1,'']]],
  ['callbacks_2ehpp_9',['callbacks.hpp',['../callbacks_8hpp.html',1,'']]],
  ['callbacks_2emd_10',['callbacks.md',['../callbacks_8md.html',1,'']]],
  ['callbacks_3a_20a_20comparison_11',['Observer Pattern vs. Callbacks: A Comparison',['../md_build_2md__files_2docs_2observer__vs__callbacks.html',1,'']]],
  ['callbacks_5ftest_2ecpp_12',['callbacks_test.cpp',['../callbacks__test_8cpp.html',1,'']]],
  ['challenges_13',['Challenges',['../md_build_2md__files_2docs_2what__is__event__driven__programming.html#autotoc_md141',1,'']]],
  ['choose_14',['How to Choose',['../md_build_2md__files_2docs_2observer__vs__callbacks.html#autotoc_md105',1,'']]],
  ['class_15',['class',['../md_build_2md__files_2docs_2qt__signals.html#autotoc_md114',1,'Receiver Class'],['../md_build_2md__files_2docs_2qt__signals.html#autotoc_md113',1,'Sender Class']]],
  ['clientconnected_16',['clientConnected',['../io__and__sockets__test_8cpp.html#ac6cec8e952f9431316b363684e877047',1,'io_and_sockets_test.cpp']]],
  ['clientthreadfunction_17',['clientThreadFunction',['../io__and__sockets__test_8cpp.html#ab71c60046211a77a2e046402a6ba468c',1,'io_and_sockets_test.cpp']]],
  ['cloning_20the_20repository_18',['Cloning the Repository',['../md_build_2md__files_2docs_2setup.html#autotoc_md122',1,'']]],
  ['close_5fsocket_19',['close_socket',['../namespaceio__and__sockets.html#a457b83d6abb24a223f0ebf214c4062ae',1,'io_and_sockets']]],
  ['cmake_20presets_20',['cmake presets',['../md_src_2io__and__sockets_2README.html#autotoc_md170',1,'Using CMake Presets'],['../md_build_2md__files_2docs_2setup.html#autotoc_md124',1,'Using CMake Presets']]],
  ['code_21',['Example Code',['../md_build_2md__files_2docs_2event__queue.html#autotoc_md68',1,'']]],
  ['common_22',['common',['../namespacecommon.html',1,'']]],
  ['common_20utilities_23',['Common Utilities',['../md_src_2common_2README.html',1,'']]],
  ['comparing_20event_20driven_20programming_20across_20languages_24',['Comparing Event-Driven Programming Across Languages',['../md_build_2md__files_2docs_2event__driven__comparison.html',1,'']]],
  ['comparison_25',['Observer Pattern vs. Callbacks: A Comparison',['../md_build_2md__files_2docs_2observer__vs__callbacks.html',1,'']]],
  ['concepts_26',['concepts',['../md_build_2md__files_2docs_2what__is__event__driven__programming.html#autotoc_md135',1,'Key Concepts'],['../md_build_2md__files_2docs_2event__queue.html#autotoc_md65',1,'Key Concepts'],['../md_build_2md__files_2docs_2observer.html#autotoc_md89',1,'Key Concepts'],['../md_build_2md__files_2docs_2design.html#autotoc_md26',1,'Key Design Patterns and Concepts']]],
  ['conclusion_27',['conclusion',['../md_build_2md__files_2docs_2observer.html#autotoc_md94',1,'Conclusion'],['../md_build_2md__files_2docs_2what__is__event__driven__programming.html#autotoc_md142',1,'Conclusion'],['../md_build_2md__files_2docs_2qt__signals.html#autotoc_md117',1,'Conclusion'],['../md_build_2md__files_2docs_2callbacks.html#autotoc_md23',1,'Conclusion'],['../md_build_2md__files_2docs_2observer__vs__callbacks.html#autotoc_md107',1,'Conclusion'],['../md_build_2md__files_2docs_2design.html#autotoc_md37',1,'Conclusion'],['../md_build_2md__files_2docs_2event__queue.html#autotoc_md71',1,'Conclusion'],['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md63',1,'Conclusion']]],
  ['concreteobserver_28',['ConcreteObserver',['../classConcreteObserver.html',1,'']]],
  ['concurrency_20and_20responsiveness_29',['Concurrency and Responsiveness',['../md_build_2md__files_2docs_2design.html#autotoc_md34',1,'']]],
  ['configuration_30',['Configuration',['../index.html#autotoc_md3',1,'']]],
  ['configure_20the_20project_31',['To Configure the Project',['../md_build_2md__files_2docs_2setup.html#autotoc_md125',1,'']]],
  ['cons_32',['cons',['../md_build_2md__files_2docs_2observer__vs__callbacks.html#autotoc_md99',1,'Cons'],['../md_build_2md__files_2docs_2observer__vs__callbacks.html#autotoc_md103',1,'Cons'],['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md59',1,'Pros and Cons'],['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md53',1,'Pros and Cons'],['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md48',1,'Pros and Cons'],['../md_build_2md__files_2docs_2event__driven__comparison.html#autotoc_md43',1,'Pros and Cons']]],
  ['considerations_33',['considerations',['../md_build_2md__files_2docs_2event__queue.html#autotoc_md70',1,'Advanced Considerations'],['../md_build_2md__files_2docs_2design.html#autotoc_md32',1,'Architectural Considerations']]],
  ['considerations_20for_20event_20driven_20programming_20in_20c_34',['Design Considerations for Event-Driven Programming in C++',['../md_build_2md__files_2docs_2design.html',1,'']]],
  ['contents_35',['contents',['../md_src_2callbacks_2README.html#autotoc_md144',1,'Contents'],['../md_src_2common_2README.html#autotoc_md149',1,'Contents'],['../md_src_2event__queue_2README.html#autotoc_md155',1,'Contents'],['../md_src_2io__and__sockets_2README.html#autotoc_md167',1,'Contents'],['../md_src_2observer_2README.html#autotoc_md177',1,'Contents'],['../md_src_2qt__signals_2README.html#autotoc_md183',1,'Contents']]],
  ['contributing_36',['Contributing',['../index.html#autotoc_md9',1,'']]],
  ['currentlevel_37',['currentLevel',['../classcommon_1_1Logger.html#aa40d1036c84bd67ddf0d860e9fae0e70',1,'common::Logger']]]
];
